test gsi

diff --git a/templates/cloud_init/cloud_init.client.yml b/templates/cloud_init/cloud_init.client.yml
--- a/templates/cloud_init/cloud_init.client.yml
+++ b/templates/cloud_init/cloud_init.client.yml
@@ -375,6 +375,48 @@ write_files:
 
       echo "DONE: end of $0"
 
+  - path: /opt/upload_gsi.sh
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+
+      function error() {
+        >&2 echo "echo >< ERROR: $* See log for details."
+        exit 1
+      }
+
+      export AZURE_SUBSCRIPTION='<sub_id>'
+      export ARM_SUBSCRIPTION_ID='<sub_id>'
+      export ARM_CLIENT_ID='<arm_client_id>'
+      export ARM_CLIENT_SECRET='<arm_client_scrt>'
+      export ARM_TENANT_ID='<arm_tenant_id>'
+      export REGION='<region>'
+      export RESOURCE_GROUP_NAME='<resource_group_name>'
+      export GSI_URL='<gsi_url>'
+
+      echo "cd to file path"
+      cd /tf/src/terraform/examples/vfxt/${TF_VFXT_CONFIG}
+      [ $? -ne 0 ] && error "cd to directory: $TF_VFXT_CONFIG"
+
+      MANAGEMENT_IP=$(terraform output -json | jq -r ".management_ip.value")
+
+      echo "ssh - initial connection needed for below scp cmd"
+      ssh -o "StrictHostKeyChecking=no" -oProxyCommand="ssh -oStrictHostKeyChecking=no -W %h:%p  admin@${MANAGEMENT_IP}" root@${MANAGEMENT_IP} ls
+
+      echo "ssh to run averecmd accept terms"
+      ssh -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} "averecmd support.acceptTerms yes"
+      [ $? -ne 0 ] && error "ssh to run averecmd accept terms"
+
+      echo "ssh to run averecmd setCustomSetting"
+      ssh -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} "averecmd support.setCustomSetting 'gsiInfo.url' 'LB' '${GSI_URL}'"
+      [ $? -ne 0 ] && error "ssh to run averecmd setCustomSetting"
+
+      echo "ssh to run averecmd gsi
+      ssh -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} "averecmd support.executeNormalMode cluster gsimin"
+      [ $? -ne 0 ] && error "ssh to run averecmd gsi"
+
+      echo "DONE: end of $0"
+
 runcmd:
   - "echo '# STEP: Setup SSH key.'"
   - "cp -v /root/.ssh/id_rsa /home/<vm_admin_user>/.ssh/id_rsa"
