ssh changes

diff --git a/templates/run_vdbench.yml b/templates/run_vdbench.yml
--- a/templates/run_vdbench.yml
+++ b/templates/run_vdbench.yml
@@ -26,54 +26,60 @@ steps:
     ID=$(terraform output -json | jq -r ".vmss_id.value")
     VMSNAME=$(terraform output -json | jq -r ".vmss_name.value")
     
+    ssh -o "StrictHostKeyChecking=no" -oProxyCommand="ssh -oStrictHostKeyChecking=no -W %h:%p  ${USERNAME}@${CONTROLLER_ADDRESS}" ${USERNAME}@${IP_ADDRESS} ls
     echo ">> SCP CMD"
     scp -o "ProxyJump ${USERNAME}@${CONTROLLER_ADDRESS}" ~/.ssh/id_rsa ${USERNAME}@${IP_ADDRESS}:.ssh/id_rsa
     
     echo ">> COPY_IDARSA.SH"
-    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} /home/azureuser/copy_idrsa.sh
+    ssh -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} /home/azureuser/copy_idrsa.sh
     
     echo ">> runvdbench"
-    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} "/usr/bin/nohup /bin/bash -c \"/bin/bash /home/${USERNAME}/run_vdbench.sh inmem.conf uniquestring1 >> /home/${USERNAME}/vdb.log 2>&1 &\" "
+    ssh -J ${USERNAME}@${CONTROLLER_ADDRESS} ${USERNAME}@${IP_ADDRESS} "/usr/bin/nohup /bin/bash -c \"/bin/bash /home/${USERNAME}/run_vdbench.sh inmem.conf uniquestring1 >> /home/${USERNAME}/vdb.log 2>&1 &\" "
     
-    export _CMD_OK_MSG="CMD_OK_$(head /dev/urandom | tr -dc a-zA-Z0-9 | head -c5)"
-    export _CMD_LOG="cmd_output.log"
-    export _FAIL_MSG="##vso[task.logissue type=error;]VMSS run-command failure. See log for details."
+    # export _CMD_OK_MSG="CMD_OK_$(head /dev/urandom | tr -dc a-zA-Z0-9 | head -c5)"
+    # export _CMD_LOG="cmd_output.log"
+    # export _FAIL_MSG="##vso[task.logissue type=error;]VMSS run-command failure. See log for details."
 
-    # Save list of VMSS instances' reference IDs.
-    _VMSS_INSTANCE_IDS=$(az vmss list-instances   \
-      --resource-group ${RESOURCE_GROUP_NAME}-vmss   \
-      --name ${VMSNAME}                      \
-      --query "[].id" --output tsv)
-    echo "> _VMSS_INSTANCE_IDS: ${_VMSS_INSTANCE_IDS}"
+    # # Save list of VMSS instances' reference IDs.
+    # _VMSS_INSTANCE_IDS=$(az vmss list-instances   \
+    #   --resource-group ${RESOURCE_GROUP_NAME}-vmss   \
+    #   --name ${VMSNAME}                      \
+    #   --query "[].id" --output tsv)
+    # echo "> _VMSS_INSTANCE_IDS: ${_VMSS_INSTANCE_IDS}"
 
-    _VMSS_INSTANCE_ID_0=$(echo ${_VMSS_INSTANCE_IDS} | sed 's/ .*$//')
-    echo "> _VMSS_INSTANCE_ID_0: ${_VMSS_INSTANCE_ID_0}"
+    # _VMSS_INSTANCE_ID_0=$(echo ${_VMSS_INSTANCE_IDS} | sed 's/ .*$//')
+    # echo "> _VMSS_INSTANCE_ID_0: ${_VMSS_INSTANCE_ID_0}"
 
-    echo
-    echo ">about to LS the dir"
-    az vmss run-command invoke     \
-      --command-id RunShellScript  \
-      --ids ${_VMSS_INSTANCE_ID_0} \
-      --scripts "ls && echo ${_CMD_OK_MSG}" | tee ${_CMD_LOG} 2>&1
-    grep -q ${_CMD_OK_MSG} ${_CMD_LOG} || (echo "${_FAIL_MSG}")
+    # echo
+    # echo ">about to LS the dir"
+    # az vmss run-command invoke     \
+    #   --command-id RunShellScript  \
+    #   --ids ${_VMSS_INSTANCE_ID_0} \
+    #   --scripts "ls && echo ${_CMD_OK_MSG}" | tee ${_CMD_LOG} 2>&1
+    # grep -q ${_CMD_OK_MSG} ${_CMD_LOG} || (echo "${_FAIL_MSG}")
 
-    echo
-    echo "> Copy id_rsa"
-    az vmss run-command invoke     \
-      --command-id RunShellScript  \
-      --ids ${_VMSS_INSTANCE_ID_0} \
-      --scripts "./copy_idrsa.sh && echo ${_CMD_OK_MSG}" | tee ${_CMD_LOG} 2>&1
-    grep -q ${_CMD_OK_MSG} ${_CMD_LOG} || (echo "${_FAIL_MSG}")
+    # echo
+    # echo "> Copy id_rsa"
+    # az vmss run-command invoke     \
+    #   --command-id RunShellScript  \
+    #   --ids ${_VMSS_INSTANCE_ID_0} \
+    #   --scripts "./copy_idrsa.sh && echo ${_CMD_OK_MSG}" | tee ${_CMD_LOG} 2>&1
+    # grep -q ${_CMD_OK_MSG} ${_CMD_LOG} || (echo "${_FAIL_MSG}")
 
-    echo
-    echo "> VM-0: Run vdbench"
-    az vmss run-command invoke       \
-        --command-id RunShellScript  \
-        --ids ${_VMSS_INSTANCE_ID_0} \
-        --scripts "./run_vdbench.sh inmem.conf uniquestring1  && echo ${_CMD_OK_MSG}" | tee ${_CMD_LOG} 2>&1
-    grep -q ${_CMD_OK_MSG} ${_CMD_LOG} || (echo "${_FAIL_MSG}")
+    # echo
+    # echo "> VM-0: Run vdbench"
+    # az vmss run-command invoke       \
+    #     --command-id RunShellScript  \
+    #     --ids ${_VMSS_INSTANCE_ID_0} \
+    #     --scripts "./run_vdbench.sh inmem.conf uniquestring1  && echo ${_CMD_OK_MSG}" | tee ${_CMD_LOG} 2>&1
+    # grep -q ${_CMD_OK_MSG} ${_CMD_LOG} || (echo "${_FAIL_MSG}")
   
     # --scripts "/usr/bin/nohup /bin/bash -c \"/bin/bash /home/${USERNAME}/run_vdbench.sh inmem.conf uniquestring1 >> /home/${USERNAME}/vdb.log 2>&1 &\" "
   displayName: 'Run vdbench'
   env:
     VDBENCH_URL: $(VDBENCH-URL)
+
+    az vmss run-command invoke     \
+      --command-id RunShellScript  \
+      --ids /subscriptions/b52fce95-de5f-4b37-afca-db203a5d0b6a/resourceGroups/tf0125x205804-vmss/providers/Microsoft.Compute/virtualMachineScaleSets/vmss/virtualMachines/0 \
+      --scripts "ls"
