Add sleep to start RunCommandLinux Failure on VMs (#1331)
* add retries and sleep

* remove failure tag

* always run scaleup/scaledown

* change sleep

* change sleep

diff --git a/templates/terraform_setup.yml b/templates/terraform_setup.yml
--- a/templates/terraform_setup.yml
+++ b/templates/terraform_setup.yml
@@ -105,20 +105,30 @@ steps:
 
     check_rc.sh $? "VM Create" || exit
 
-    cmdlog=/tmp/vm_runcmd.log
-    az vm run-command invoke                  \
-      --resource-group ${RESOURCE_GROUP_NAME} \
-      --name ${VM_NAME}                      \
-      --command-id RunShellScript             \
-      --scripts "cloud-init status --wait"    \
-      --query 'value[0].message' --output tsv | tee ${cmdlog}
-    check_rc.sh ${PIPESTATUS[0]} "Wait for the VM's cloud-init to complete" || exit 0
+    for i in {1..3}; do
+      sleep 60
+      cmdlog=/tmp/vm_runcmd.log
+      az vm run-command invoke                  \
+        --resource-group ${RESOURCE_GROUP_NAME} \
+        --name ${VM_NAME}                      \
+        --command-id RunShellScript             \
+        --scripts "cloud-init status --wait"    \
+        --query 'value[0].message' --output tsv | tee ${cmdlog}
+
+      run_rc=${PIPESTATUS[0]}
+      if [ "${run_rc}" -ne 0 ]; then
+        echo "##vso[task.logissue type=error;]Running cloud init wait Attempt $i of 3."
+      else
+        break
+      fi
+    done
     grep -q 'status: done' ${cmdlog}
     check_rc.sh $? "Wait for cloud-init completion. Create vfxt"
 
+
     # Cooldown for "az vm run-command invoke" before the next one.
     # This solves a corner/race case when the command is run back-to-back.
-    sleep 20
+    sleep 30
 
     az vm run-command invoke                          \
       --command-id     RunShellScript                 \
